/*
 * generated by Xtext
 */
package xmodel.dsl.ui.contentassist

import xmodel.dsl.ui.contentassist.AbstractXdslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class XdslProposalProvider extends AbstractXdslProposalProvider {
}
