/*
 * generated by Xtext
 */
package xmodel.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XdslUiModule extends xmodel.dsl.ui.AbstractXdslUiModule {
	public XdslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
