/*
 * generated by Xtext
 */
package xmodel.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XdslRuntimeModule extends xmodel.dsl.AbstractXdslRuntimeModule {

}
