/*
* generated by Xtext
*/
package xmodel.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XdslStandaloneSetup extends XdslStandaloneSetupGenerated{

	public static void doSetup() {
		new XdslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

